package sroof

import scala.util.boundary
import scala.util.boundary.break
import sroof.core.{Term, Context, GlobalEnv, Subst, MatchCase, DefEntry}
import sroof.syntax.{ElabResult, SProof, STactic, STacticCase, SType, SCalcStep, SExpr}
import sroof.tactic.{TacticM, Builtins, TacticError, ProofStatePretty, Eq, Goal}
import sroof.checker.Bidirectional
import sroof.kernel.Kernel

/** Checks and proves all declarations from an elaboration result.
  *
  * Takes an ElabResult (containing the global env, def bodies, and defspec proofs)
  * and fully verifies each declaration through tactic execution + kernel re-check.
  */
object Checker:
  /** Candidate proof term generated by checker/tactic pipeline.
    *
    * Final accept/reject is delegated to [[finalizeProofCandidates]].
    */
  final case class ProofCandidate(
    name: String,
    proofTerm: Term,
    proposition: Term,
    skipKernel: Boolean,
  )


  /** Check all declarations in the elaboration result.
    *
    * @param result the elaborated result containing env, defs, and defspecs
    * @return either an error message or the final GlobalEnv after all checks
    */
  def checkAll(result: ElabResult): Either[String, GlobalEnv] =
    checkAllWithWarnings(result).map(_._1)

  /** Phase 1: generate proof candidates from tactics/terms (no kernel decision). */
  def generateProofCandidates(
    result: ElabResult,
  )(using env: GlobalEnv): Either[String, (List[ProofCandidate], List[String])] =
    boundary:
      val sorryWarnings = scala.collection.mutable.ListBuffer.empty[String]
      val candidates = scala.collection.mutable.ListBuffer.empty[ProofCandidate]
      // A `@[simp] defspec` used to be registered in `simpSet` by the elaborator,
      // which runs before any proof does, while its `DefEntry` is only added below
      // as each proof succeeds. Between those two points the default lemma set
      // held a name that resolved to nothing: `simplify` with no lemmas picked it
      // up and silently degraded to `trivial`, and the guard that reports an
      // unresolvable name is deliberately skipped for the default set — on the
      // grounds, stated in `Builtins.checkLemmaNames`, that those names "exist by
      // construction". For a defspec they did not.
      //
      // The set is also what `simplify` uses *implicitly*, while sorry-taint is
      // propagated from the lemma names a proof actually writes. A sorry-tainted
      // `@[simp]` lemma reached that way would leave no trace in the warnings.
      //
      // So a defspec joins `simpSet` here, once its proof has been produced and is
      // not sorry-tainted — the discipline `frontend.ModuleVerifier` already
      // states for the Scala path, where a theorem "enters simpSet only after the
      // kernel has accepted its proof".
      val simpDefspecs = result.simpDefspecs
      var proofEnv = env
      // Track which defspecs are tainted by sorry (directly or transitively)
      val sorryTainted = scala.collection.mutable.Set.empty[String]

      for name <- defspecNamesInSourceOrder(result) do
        result.defspecs.get(name) match
          case None =>
            break(Left(s"Internal error: defspec '$name' missing from elaboration map"))
          case Some((elabParams, propTerm, proof)) =>
            val proofCtx = elabParams.foldLeft(Context.empty) { (ctx, p) =>
              ctx.extend(p._1, p._2)
            }
            val sorryCount = countSorry(proof)
            if sorryCount > 0 then
              sorryWarnings += s"warning: '$name' uses sorry ($sorryCount occurrence(s)) — proof is unsound"
              sorryTainted += name

            val refs = collectLemmaRefs(proof)
            val taintedRefs = refs.intersect(sorryTainted.toSet).toList.sorted
            if taintedRefs.nonEmpty && sorryCount == 0 then
              sorryWarnings += s"warning: '$name' depends on sorry-tainted defspec(s): ${taintedRefs.mkString(", ")} — proof is transitively unsound"
              sorryTainted += name

            wellFormedProp(proofCtx, propTerm)(using proofEnv) match
              case Left(why) =>
                break(Left(s"Statement of '$name' is not a proposition: $why"))
              case Right(())  => ()

            executeProof(proofCtx, propTerm, proof)(using proofEnv) match
              case Left(err) =>
                break(Left(s"Proof of '$name' failed: $err"))
              case Right(proofTerm) =>
                val fullProofTerm = elabParams.foldRight(proofTerm) { (p, body) =>
                  Term.Lam(p._1, p._2, body)
                }
                val fullPropTerm = elabParams.foldRight(propTerm) { (p, cod) =>
                  Term.Pi(p._1, p._2, cod)
                }
                val skipKernel = sorryCount > 0 || sorryTainted.contains(name)
                candidates += ProofCandidate(name, fullProofTerm, fullPropTerm, skipKernel)
                // Make previously proved theorems available to later proofs.
                // This enables proof reuse via term proofs / exact theorem calls.
                proofEnv = proofEnv.addDef(DefEntry(name, fullPropTerm, fullProofTerm))
                if simpDefspecs.contains(name) && !skipKernel then
                  proofEnv = proofEnv.addToSimpSet(name)

      Right((candidates.toList, sorryWarnings.toList))

  /** Phase 2: final accept/reject through kernel only. */
  def finalizeProofCandidates(
    candidates: List[ProofCandidate],
  )(using env: GlobalEnv): Either[String, Unit] =
    candidates.foldLeft[Either[String, Unit]](Right(())) { (acc, candidate) =>
      acc.flatMap { _ =>
        if candidate.skipKernel then Right(())
        else
          Kernel.verify(Context.empty, candidate.proofTerm, candidate.proposition) match
            case Left(err)  => Left(s"Kernel rejected proof of '${candidate.name}': ${err.message}")
            case Right(())  => Right(())
      }
    }

  /** Check every `def` body against its declared type.
   *
   *  Until v0.14 nothing did, so `def f(n: Nat): Nat { Bool.tru }` was accepted and a
   *  definition could say one thing and mean another.  Only a `defspec` reached the
   *  kernel, and every proposition is written in terms of these definitions.
   *
   *  Finding it also fixed five real defects: `stdlib/PolyList.sroof`'s three
   *  polymorphic functions and the two `concat`s declared their type parameter last,
   *  which forces a bare `PolyList`/`Vec` in the signature where the value has the
   *  applied type — the exact anti-pattern the files' own header warns about.
   *
   *  Runs before proofs: a proposition built from a definition that does not
   *  type-check is not worth a proof error about.
   */
  def checkDefBodies(result: ElabResult)(using env: GlobalEnv): Either[String, Unit] =
    // `defs` is a Map, so sort for a deterministic first message.  Order is otherwise
    // irrelevant: a definition can only refer to ones already declared.
    result.defs.toList.sortBy(_._1).foldLeft[Either[String, Unit]](Right(())) {
      case (acc, (name, body)) =>
        acc.flatMap { _ =>
          env.lookupDef(name) match
            case None      => Right(())   // not registered; nothing to check against
            case Some(entry) =>
              Kernel.verify(Context.empty, body, entry.tpe) match
                case Right(())  => Right(())
                case Left(err)  => Left(s"Definition '$name' does not match its declared type: ${err.message}")
        }
    }

  /** Evaluate the file's `#check` declarations.
   *
   *  A `#check` is an assertion the author wrote, so one that does not elaborate or
   *  does not type-check is a failure of the file — not a note filed somewhere the
   *  plain CLI never prints. Before v0.15 the result was computed, discarded by the
   *  non-JSON path, and the file still reported OK, so `#check Nat.succ(Bool.tru)`
   *  was completely silent.
   */
  def evalChecks(result: ElabResult)(using env: GlobalEnv): Either[String, List[(String, String)]] =
    import sroof.checker.Bidirectional
    import sroof.syntax.Elaborator
    result.checks.foldLeft[Either[String, List[(String, String)]]](Right(Nil)) { (acc, sexpr) =>
      acc.flatMap { done =>
        Elaborator.elabExprPublic(sexpr, env, Nil) match
          case Left(err) =>
            Left(s"#check ${sexpr.toString} failed to elaborate: ${err.message}")
          case Right(term) =>
            Bidirectional.infer(Context.empty, term) match
              case Left(err)  => Left(s"#check ${term.show} does not type-check: ${err.getMessage}")
              case Right(tpe) => Right(done :+ (term.show, tpe.show))
      }
    }

  /** Like checkAll but also returns sorry warnings. */
  def checkAllWithWarnings(result: ElabResult): Either[String, (GlobalEnv, List[String])] =
    given GlobalEnv = result.env
    for
      _ <- checkDefBodies(result)
      generated <- generateProofCandidates(result)
      (candidates, warnings) = generated
      _ <- finalizeProofCandidates(candidates)
    yield (result.env, warnings)

  /** Check that a defspec's statement is a proposition before proving it.
    *
    * An ill-typed statement was not accepted before this — `executeProof` catches
    * the evaluator exception it causes — but it was *diagnosed* as
    * "Internal error while running the proof: … This is a bug in sroof", which
    * blames the tool for something the author wrote. A statement like
    * `plus(Bool.tru, Nat.zero) = plus(Bool.tru, Nat.zero)` is not a bug in sroof;
    * it is not a proposition, and saying so names the actual problem.
    *
    * `Bidirectional.inferUniverse` cannot answer this on its own: it returns
    * `Right(0)` for an applied `Eq` **without inspecting the arguments**, taking
    * the shape as evidence. What makes `Eq A a b` a proposition is that both sides
    * are typeable at one type, so that is what is checked.
    */
  private def wellFormedProp(ctx: Context, prop: Term)(using GlobalEnv): Either[String, Unit] =
    // Rejection-safe: `Eval` throws on a term it cannot reduce, and an ill-typed
    // statement is exactly such a term. A throw here becomes a rejection, never an
    // acceptance.
    try
      Eq.extract(prop) match
        case Some((_, lhs, rhs)) =>
          for
            tpe <- Bidirectional.infer(ctx, lhs).left.map(_.getMessage)
            _   <- Bidirectional.check(ctx, rhs, tpe).left.map(_.getMessage)
          yield ()
        case None =>
          // Deliberately unchecked, and the reason is a real limitation rather
          // than caution. A defspec may state a bare type to be inhabited, and
          // for a family with a phantom index — one that declares indices its
          // constructors do not state — the *applied* form cannot be typed at
          // all: `infer` on `Ind(name, …)` folds over the parameters only, so
          // `PVec(Nat)(zero)` reaches `Expected function type`. Requiring this
          // shape to type-check rejected a file the tool proves today
          // (`IndexedFamilySuite`, "a family whose constructors omit their
          // indices is unchanged"). The blind spot being closed here is specific
          // to `Eq` anyway: `inferUniverse` answers `Right(0)` for an applied
          // `Eq` without looking at the arguments.
          Right(())
    catch
      case scala.util.control.NonFatal(e) =>
        Left(Option(e.getMessage).getOrElse(e.getClass.getName))

  /** Count sorry usages in a surface proof. */
  private def countSorry(proof: SProof): Int = proof match
    case SProof.SBy(tactic) => countSorryTactic(tactic)
    case SProof.STerm(_)    => 0

  private def countSorryTactic(t: STactic): Int = t match
    case STactic.SSorry           => 1
    case STactic.SSeq(ts)         => ts.map(countSorryTactic).sum
    case STactic.SInduction(_, cases, _) => cases.map(c => countSorryTactic(c.tactic)).sum
    case STactic.SCases(_, cases)     => cases.map(c => countSorryTactic(c.tactic)).sum
    case STactic.SFirst(ts)       => ts.map(countSorryTactic).sum
    case STactic.SRepeat(t)       => countSorryTactic(t)
    case STactic.STry(t)          => countSorryTactic(t)
    case STactic.SAllGoals(t)     => countSorryTactic(t)
    case STactic.SHave(_, _, p, cont) => countSorry(p) + countSorryTactic(cont)
    case STactic.SCalc(steps)     => steps.map(s => countSorry(s.proof)).sum
    case STactic.SObtain(_, _, cont)     => countSorryTactic(cont)
    case STactic.SSpecialize(_, _, cont) => countSorryTactic(cont)
    // Enumerated rather than defaulted. The `case _ => 0` this replaces swallowed
    // three tactics that carry a proof: `obtain` and `specialize` each continue
    // into another tactic, and `calc` holds a proof per step. A `sorry` in any of
    // them was counted as zero, so the file reported OK with no warning at all and
    // `--fail-on-sorry` — whose whole job is to find `sorry` — exited 0. Adding a
    // tactic now fails to compile here instead of silently reporting no `sorry`.
    case STactic.STrivial | STactic.STriv | STactic.SRfl | STactic.SSkip |
         STactic.SAssumption | STactic.SContradiction | STactic.SDecide |
         STactic.SSplit | STactic.SConstructor | STactic.SLeft | STactic.SRight |
         STactic.STauto => 0
    case STactic.SAssume(_) | STactic.SApply(_) | STactic.SExact(_) |
         STactic.SSimplify(_) | STactic.SSimp(_) | STactic.SRewrite(_) |
         STactic.SRw(_) | STactic.SUse(_) | STactic.SExists(_) |
         STactic.SByContra(_) => 0

  /** Collect all lemma names referenced in a proof (via simplify, rewrite, etc.). */
  private def collectLemmaRefs(proof: SProof): Set[String] = proof match
    case SProof.SBy(tactic) => collectLemmaRefsTactic(tactic)
    case SProof.STerm(expr) => collectLemmaRefsExpr(expr)

  private def collectLemmaRefsExpr(expr: SExpr, bound: Set[String] = Set.empty): Set[String] = expr match
    case SExpr.SEVar(name) =>
      if bound.contains(name) then Set.empty else Set(name)
    case SExpr.SEApp(fn, args) =>
      collectLemmaRefsExpr(fn, bound) ++ args.flatMap(arg => collectLemmaRefsExpr(arg, bound))
    case SExpr.SELam(params, body) =>
      val nextBound = bound ++ params.map(_.name)
      collectLemmaRefsExpr(body, nextBound)
    case SExpr.SEMatch(scrutinee, cases) =>
      val scrRefs = collectLemmaRefsExpr(scrutinee, bound)
      val caseRefs = cases.flatMap { mc =>
        collectLemmaRefsExpr(mc.body, bound ++ mc.bindings)
      }.toSet
      scrRefs ++ caseRefs
    case SExpr.SECon(_, _, args) =>
      args.flatMap(arg => collectLemmaRefsExpr(arg, bound)).toSet
    case SExpr.SInfix(lhs, _, rhs) =>
      collectLemmaRefsExpr(lhs, bound) ++ collectLemmaRefsExpr(rhs, bound)
    case SExpr.SEList(elems) =>
      elems.flatMap(elem => collectLemmaRefsExpr(elem, bound)).toSet
    case SExpr.SEInt(_) =>
      Set.empty
    case SExpr.SELet(name, value, body) =>
      collectLemmaRefsExpr(value, bound) ++ collectLemmaRefsExpr(body, bound + name)
    case SExpr.SEAscr(inner, _) =>
      collectLemmaRefsExpr(inner, bound)
    case SExpr.SEIf(cond, thenBr, elseBr) =>
      collectLemmaRefsExpr(cond, bound) ++
        collectLemmaRefsExpr(thenBr, bound) ++
        collectLemmaRefsExpr(elseBr, bound)

  private def collectLemmaRefsTactic(t: STactic): Set[String] = t match
    case STactic.SSimplify(lemmas)    => lemmas.toSet
    case STactic.SSimp(lemmas)        => lemmas.toSet
    case STactic.SRw(lemmas)          => lemmas.toSet
    case STactic.SRewrite(lemmas)     => lemmas.toSet
    case STactic.SApply(expr)         => collectLemmaRefsExpr(expr)
    case STactic.SExact(expr)         => collectLemmaRefsExpr(expr)
    case STactic.SCalc(steps)         => steps.flatMap(step => collectLemmaRefs(step.proof)).toSet
    case STactic.SSeq(ts)             => ts.flatMap(collectLemmaRefsTactic).toSet
    case STactic.SInduction(_, cases, _) => cases.flatMap(c => collectLemmaRefsTactic(c.tactic)).toSet
    case STactic.SCases(_, cases)     => cases.flatMap(c => collectLemmaRefsTactic(c.tactic)).toSet
    case STactic.SFirst(ts)           => ts.flatMap(collectLemmaRefsTactic).toSet
    case STactic.SRepeat(t)           => collectLemmaRefsTactic(t)
    case STactic.STry(t)              => collectLemmaRefsTactic(t)
    case STactic.SAllGoals(t)         => collectLemmaRefsTactic(t)
    case STactic.SHave(_, _, p, cont) => collectLemmaRefs(p) ++ collectLemmaRefsTactic(cont)
    case STactic.SUse(expr)           => collectLemmaRefsExpr(expr)
    case STactic.SExists(expr)        => collectLemmaRefsExpr(expr)
    // The hypothesis name is included: it is usually a local, but it resolves
    // against globals too, so a tainted lemma reached this way should count. Over-
    // reporting taint is the safe direction; under-reporting is what this fixes.
    case STactic.SObtain(_, hyp, cont)        =>
      Set(hyp) ++ collectLemmaRefsTactic(cont)
    case STactic.SSpecialize(hyp, args, cont) =>
      Set(hyp) ++ args.flatMap(a => collectLemmaRefsExpr(a)).toSet ++ collectLemmaRefsTactic(cont)
    // Enumerated, not defaulted — see `countSorryTactic`.
    case STactic.STrivial | STactic.STriv | STactic.SRfl | STactic.SSkip |
         STactic.SAssumption | STactic.SContradiction | STactic.SDecide |
         STactic.SSplit | STactic.SConstructor | STactic.SLeft | STactic.SRight |
         STactic.STauto => Set.empty
    case STactic.SAssume(_) | STactic.SSorry | STactic.SByContra(_) => Set.empty

  private def defspecNamesInSourceOrder(result: ElabResult): List[String] =
    if result.defspecOrder.isEmpty then
      result.defspecs.keys.toList.sorted
    else
      val ordered = result.defspecOrder.filter(result.defspecs.contains)
      val remaining = result.defspecs.keySet -- ordered
      ordered ++ remaining.toList.sorted

  /** Execute a surface proof to produce a core proof term.
    *
    * @param ctx   the context in which the proof is checked
    * @param prop  the proposition to prove
    * @param proof the surface-level proof strategy
    * @param env   the global environment
    * @return either an error string or the core proof term
    */
  def executeProof(ctx: Context, prop: Term, proof: SProof)(using env: GlobalEnv): Either[String, Term] =
    // Last line of defence.  Tactics are untrusted proof-term generators and the
    // evaluator throws on terms it cannot reduce; neither is a reason to hand the
    // user a stack trace.  Anything that escapes becomes a failed proof, which is
    // the safe direction — a thrown exception can only ever lose a proof, not
    // manufacture one, because the kernel still has to accept whatever comes back.
    try executeProofUnguarded(ctx, prop, proof)
    catch
      case scala.util.control.NonFatal(e) =>
        Left(s"Internal error while running the proof: ${e.getMessage}. " +
             "This is a bug in sroof — the proof is rejected rather than accepted.")

  private def executeProofUnguarded(ctx: Context, prop: Term, proof: SProof)(using env: GlobalEnv): Either[String, Term] =
    proof match
      case SProof.SBy(tactic) =>
        val t = tacticFromSurface(tactic)
        TacticM.proveWithState(ctx, prop)(t) match
          case Right(term)         => Right(term)
          case Left((err, state))  => Left(ProofStatePretty.format(state, err))

      case SProof.STerm(sexpr) =>
        import sroof.syntax.Elaborator
        // Elaborate the expression in the current context
        val nameEnv = ctx.entries.map(_.name).toList
        Elaborator.elabExprPublic(sexpr, env, nameEnv) match
          case Left(err) => Left(s"Term proof elaboration failed: ${err.message}")
          case Right(term) => Right(term)

  /** Convert a surface tactic to a TacticM computation. */
  def tacticFromSurface(t: STactic)(using env: GlobalEnv): TacticM[Unit] = t match
    case STactic.STrivial =>
      Builtins.trivial

    case STactic.STriv =>
      Builtins.trivial

    case STactic.SAssume(names) =>
      names.foldLeft(TacticM.pure(())) { (acc, name) =>
        acc.flatMap(_ => Builtins.assume(name))
      }

    case STactic.SSimplify(lemmas) =>
      Builtins.simplify(lemmas)

    case STactic.SSimp(lemmas) =>
      Builtins.simplify(lemmas)

    case STactic.SInduction(varName, cases, generalizing) =>
      val caseSpecs = cases.map(c => (c.ctorName, c.extraBindings))
      Builtins.induction(varName, caseSpecs, generalizing).flatMap { _ =>
        closeRemainingGoals(cases)
      }

    case STactic.SApply(_expr) =>
      // SApply requires a fully elaborated core term; deferred in CLI.
      TacticM.pure(())

    case STactic.SSorry =>
      sorryCurrentGoal

    case STactic.SHave(name, stpe, proof, cont) =>
      haveTactic(name, stpe, proof, cont)

    case STactic.SRfl =>
      Builtins.trivial

    case STactic.SRw(lemmas) =>
      Builtins.rewrite(lemmas)

    case STactic.SRewrite(lemmas) =>
      Builtins.rewrite(lemmas)

    case STactic.SExact(sexpr) =>
      exactTactic(sexpr)

    case STactic.SSeq(tactics) =>
      tactics.foldLeft(TacticM.pure(())) { (acc, t) =>
        acc.flatMap(_ => tacticFromSurface(t))
      }

    case STactic.SCalc(steps) =>
      calcTactic(steps)

    case STactic.STry(inner) =>
      TacticM.get.flatMap { s =>
        val (newState, result) = TacticM.run(tacticFromSurface(inner), s)
        result match
          case Right(()) => TacticM.set(newState)
          case Left(_)   => TacticM.pure(())
      }

    case STactic.SFirst(tactics) =>
      def tryAlternatives(remaining: List[STactic]): TacticM[Unit] =
        remaining match
          case Nil => TacticM.fail(TacticError.Custom("first: all alternatives failed"))
          case tac :: rest =>
            TacticM.get.flatMap { s =>
              val (newState, result) = TacticM.run(tacticFromSurface(tac), s)
              result match
                case Right(()) => TacticM.set(newState)
                case Left(_)   => tryAlternatives(rest)
            }
      tryAlternatives(tactics)

    case STactic.SRepeat(inner) =>
      def loop: TacticM[Unit] =
        TacticM.get.flatMap { s =>
          val (newState, result) = TacticM.run(tacticFromSurface(inner), s)
          result match
            case Right(()) => TacticM.set(newState).flatMap(_ => loop)
            case Left(_)   => TacticM.pure(())
        }
      loop

    case STactic.SAllGoals(inner) =>
      TacticM.get.flatMap { s =>
        s.goals.foldLeft(TacticM.pure(())) { (acc, _) =>
          acc.flatMap(_ => tacticFromSurface(inner))
        }
      }

    case STactic.SSkip =>
      TacticM.pure(())

    case STactic.SAssumption =>
      Builtins.assumption

    case STactic.SContradiction =>
      Builtins.contradiction

    case STactic.SDecide =>
      Builtins.decide

    case STactic.SCases(varName, cases) =>
      val caseSpecs = cases.map(c => (c.ctorName, c.extraBindings))
      Builtins.cases(varName, caseSpecs).flatMap { _ =>
        closeRemainingGoals(cases)
      }

    case STactic.SSplit =>
      Builtins.split_

    case STactic.SConstructor =>
      Builtins.split_

    case STactic.SLeft =>
      Builtins.leftTactic

    case STactic.SRight =>
      Builtins.rightTactic

    case STactic.STauto =>
      Builtins.tauto

    case STactic.SByContra(varName) =>
      Builtins.byContra(varName)

    case STactic.SUse(sexpr) =>
      import sroof.syntax.Elaborator
      for
        goalPair  <- TacticM.currentGoal
        (_, goal)  = goalPair
        nameEnv    = goal.ctx.entries.map(_.name).toList
        witness   <- Elaborator.elabExprPublic(sexpr, env, nameEnv) match
          case Right(t) => TacticM.pure(t)
          case Left(e)  => TacticM.fail(TacticError.Custom(s"use: elaboration failed: ${e.message}"))
        _         <- Builtins.use_(witness)
      yield ()

    case STactic.SExists(sexpr) =>
      tacticFromSurface(STactic.SUse(sexpr))

    case STactic.SObtain(bindings, hypName, cont) =>
      Builtins.obtain(bindings, hypName).flatMap { _ =>
        tacticFromSurface(cont)
      }

    case STactic.SSpecialize(hypName, sexprs, cont) =>
      import sroof.syntax.Elaborator
      for
        goalPair  <- TacticM.currentGoal
        (_, goal)  = goalPair
        nameEnv    = goal.ctx.entries.map(_.name).toList
        args      <- sexprs.foldLeft(TacticM.pure(List.empty[Term])) { (acc, sexpr) =>
          acc.flatMap { argsSoFar =>
            Elaborator.elabExprPublic(sexpr, env, nameEnv) match
              case Right(t) => TacticM.pure(argsSoFar :+ t)
              case Left(e)  => TacticM.fail(TacticError.Custom(s"specialize: ${e.message}"))
          }
        }
        _         <- Builtins.specialize(hypName, args, tacticFromSurface(cont))
      yield ()

  /** Close remaining sub-goals using the specified case tactics in order.
   *
   *  Each STacticCase is consumed one-by-one as subgoals are closed.
   *  If no cases remain, fall back to trivial (then sorry if trivial fails).
   */
  private def closeRemainingGoals(cases: List[STacticCase])(using env: GlobalEnv): TacticM[Unit] =
    TacticM.get.flatMap { s =>
      if s.goals.isEmpty then TacticM.pure(())
      else
        val (tactic, rest) = cases match
          case caseSpec :: remaining => (tacticFromSurface(caseSpec.tactic), remaining)
          case Nil                   => (attemptTrivialOrSorryTactic, Nil)
        tactic.flatMap(_ => closeRemainingGoals(rest))
    }

  /** TacticM version of attemptTrivialOrSorry for use as a fallback. */
  private def attemptTrivialOrSorryTactic(using env: GlobalEnv): TacticM[Unit] =
    TacticM.get.flatMap { s =>
      val (finalState, result) = TacticM.run(Builtins.trivial, s)
      result match
        case Right(()) => TacticM.set(finalState)
        case Left(_)   => sorryCurrentGoal
    }

  /** Try trivial; if it fails fall back to sorry (discharges without proof). */
  private def attemptTrivialOrSorry(using env: GlobalEnv): TacticM[Unit] =
    attemptTrivialOrSorryTactic

  /** Discharge the current goal with a placeholder (sorry).
    *
    * For equality goals `lhs = rhs`, creates `refl(lhs)` — a proof of `lhs = lhs`.
    * This is unsound when `lhs ≠ rhs`, but passes the kernel when `lhs ≡ rhs`.
    * The caller is responsible for emitting a sorry warning.
    */
  private def sorryCurrentGoal: TacticM[Unit] =
    TacticM.currentGoal.flatMap { case (mv, goal) =>
      val eqObj = sroof.tactic.Eq
      val placeholder = goal.target match
        case Term.App(Term.App(Term.Ind("Eq", _, _), lhs), _) => eqObj.mkRefl(lhs)
        case Term.App(Term.App(Term.App(Term.Ind("Eq", _, _), _), lhs), _) => eqObj.mkRefl(lhs)
        case t => eqObj.mkRefl(t)
      TacticM.solveGoalWith(mv, placeholder)
    }

  /** have h: T = { proof }; cont
    *
    * 1. Elaborate the surface type into a core Term
    * 2. Prove the sub-proposition in the current context
    * 3. Introduce h: T via Let into the proof
    * 4. Continue with cont tactic
    */
  private def haveTactic(
    name:  String,
    stpe:  sroof.syntax.SType,
    proof: SProof,
    cont:  STactic,
  )(using env: GlobalEnv): TacticM[Unit] =
    import sroof.syntax.Elaborator
    for
      goalPair   <- TacticM.currentGoal
      (mv, goal)  = goalPair
      // Elaborate the surface type in the current context
      tpeTerm    <- Elaborator.elabTypePublic(stpe, env, goal.ctx) match
        case Right(t) => TacticM.pure(t)
        case Left(e)  => TacticM.fail(TacticError.Custom(s"have: type elaboration failed: ${e.message}"))
      // Prove the sub-proposition
      proofTerm  <- executeProof(goal.ctx, tpeTerm, proof) match
        case Right(t) => TacticM.pure(t)
        case Left(e)  => TacticM.fail(TacticError.Custom(s"have: sub-proof failed: $e"))
      // Create new goal with h: T in context via Let
      newCtx      = goal.ctx.extend(name, tpeTerm)
      newTarget   = sroof.core.Subst.shift(1, goal.target)
      mv_cont    <- TacticM.addGoal(newCtx, newTarget)
      // Evidence: Let(h, T, proofTerm, <cont_proof>)
      _          <- TacticM.solveGoalWith(mv, sroof.core.Term.Let(name, tpeTerm, proofTerm, sroof.core.Term.Meta(mv_cont.id)))
      // Run the continuation tactic
      _          <- tacticFromSurface(cont)
    yield ()

  /** exact e — provide the exact proof term, checked against the current goal. */
  private def exactTactic(sexpr: SExpr)(using env: GlobalEnv): TacticM[Unit] =
    import sroof.syntax.Elaborator
    for
      goalPair   <- TacticM.currentGoal
      (mv, goal)  = goalPair
      nameEnv     = goal.ctx.entries.map(_.name).toList
      proofTerm  <- Elaborator.elabExprPublic(sexpr, env, nameEnv) match
        case Right(t) => TacticM.pure(t)
        case Left(e)  => TacticM.fail(TacticError.Custom(s"exact: elaboration failed: ${e.message}"))
      _          <- TacticM.solveGoalWith(mv, proofTerm)
    yield ()

  /** calc { step1 step2 ... } — chain equality proofs by transitivity.
   *
   *  Each step `lhs = rhs { proof }` is proved independently; steps are then
   *  chained using J-rule transitivity into a single proof of the overall goal.
   */
  private def calcTactic(
    steps: List[SCalcStep],
  )(using env: GlobalEnv): TacticM[Unit] =
    for
      goalPair  <- TacticM.currentGoal
      (mv, goal) = goalPair
      nameEnv    = goal.ctx.entries.map(_.name).toList
      chainProof <- buildCalcChain(goal, nameEnv, steps, None)
      _          <- TacticM.solveGoalWith(mv, chainProof)
    yield ()

  /** Recursively elaborate calc steps and build a transitivity chain.
   *
   *  @param prevRhs the RHS of the previous step (used when current step has lhs = None)
   */
  private def buildCalcChain(
    goal:    Goal,
    nameEnv: List[String],
    steps:   List[SCalcStep],
    prevRhs: Option[Term],
  )(using env: GlobalEnv): TacticM[Term] =
    import sroof.syntax.Elaborator
    steps match
      case Nil =>
        TacticM.fail(TacticError.Custom("calc: empty calc block"))
      case step :: rest =>
        for
          lhs <- step.lhs match
            case None =>
              prevRhs match
                case Some(r) => TacticM.pure(r)
                case None    => TacticM.fail(TacticError.Custom("calc: first step must have explicit LHS"))
            case Some(e) =>
              Elaborator.elabExprPublic(e, env, nameEnv) match
                case Right(t) => TacticM.pure(t)
                case Left(e)  => TacticM.fail(TacticError.Custom(s"calc: LHS elaboration: ${e.message}"))
          rhs <- Elaborator.elabExprPublic(step.rhs, env, nameEnv) match
            case Right(t) => TacticM.pure(t)
            case Left(e)  => TacticM.fail(TacticError.Custom(s"calc: RHS elaboration: ${e.message}"))
          // The 2-arg form is the one the checker can type; `Eq.mkType` with a
          // `Meta` for the element type produces a proposition `inferUniverse`
          // does not recognise, and a `Meta` the evaluator refuses outright.
          stepProp  = Eq.mkPropType(lhs, rhs)
          stepProof <- executeProof(goal.ctx, stepProp, step.proof) match
            case Right(t) => TacticM.pure(t)
            case Left(e)  => TacticM.fail(TacticError.Custom(s"calc: step proof failed: $e"))
          result    <- rest match
            case Nil => TacticM.pure(stepProof)
            case _   =>
              // The transitivity motive binds a variable ranging over the element
              // type, so that type has to be inferred — the midpoint *term* is not
              // it.  Only needed when there is a next step.
              for
                midTpe <- Bidirectional.infer(goal.ctx, rhs) match
                  case Right(t) => TacticM.pure(t)
                  case Left(e)  => TacticM.fail(TacticError.Custom(
                    s"calc: cannot infer the type of '${rhs.show}': ${e.getMessage}"))
                restProof <- buildCalcChain(goal, nameEnv, rest, Some(rhs))
              yield buildTransProof(stepProof, restProof, lhs, midTpe)
        yield result

  /** Build a transitivity proof: given `h1 : lhs = mid` and `h2 : mid = rhs`,
   *  returns a proof of `lhs = rhs` via J-rule elimination on `h2`.
   *
   *  Proof term: `Mat(h2, [refl => shift(1, h1)], Lam("y", midTpe, lhs_shifted = Var(0)))`
   *
   *  `midTpe` is the type the chain's values live in — `Nat` for a chain of `Nat`s.
   *  This used to be handed the midpoint *term*, producing `λy:Nat.zero. …`: a
   *  binder whose declared type is a value.  Together with a `Meta` element type in
   *  the motive body, which the evaluator refuses, that made every multi-step `calc`
   *  fail with a beta-redex the checker could not reduce.  Single-step chains never
   *  reach here, which is why the tactic looked like it worked.
   */
  private def buildTransProof(h1: Term, h2: Term, lhs: Term, midTpe: Term): Term =
    val shiftedLhs  = Subst.shift(1, lhs)
    val motiveBody  = Eq.mkPropType(shiftedLhs, Term.Var(0))
    val motive      = Term.Lam("y", midTpe, motiveBody)
    val branchBody  = Subst.shift(1, h1)
    Term.Mat(h2, List(MatchCase("refl", 1, branchBody)), motive)

end Checker
